# -*- coding: utf-8 -*-
"""NLP_Final_Project_Code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17z5n4I2_QQ-S6N9A8Orpajb-uHPokqXU
"""

# =========================
# 0. Dependencies
# =========================
!pip install --upgrade transformers

# =========================
# 1. Imports
# =========================
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

from datasets import Dataset
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    Trainer,
    TrainingArguments,
    pipeline
)

# =========================
# 2. Load + Combine Data
# =========================
df_me = pd.read_csv("/content/reviews_me.csv")
df_sib1 = pd.read_csv("/content/reviews_sibling1.csv")
df_sib2 = pd.read_csv("/content/reviews_sibling2.csv")

cols = ["Name", "Year", "Rating", "Review"]

df_me = df_me[cols]
df_sib1 = df_sib1[cols]
df_sib2 = df_sib2[cols]

rename_map = {
    "Name": "movie_title",
    "Year": "year",
    "Rating": "star_rating",
    "Review": "review_text"
}

df_me = df_me.rename(columns=rename_map)
df_sib1 = df_sib1.rename(columns=rename_map)
df_sib2 = df_sib2.rename(columns=rename_map)

df_me["source"] = "you"
df_sib1["source"] = "sibling"
df_sib2["source"] = "sibling"

df = pd.concat([df_me, df_sib1, df_sib2], ignore_index=True)

df = df.dropna(subset=["review_text", "star_rating"])
df = df[df["review_text"].str.strip() != ""]

print("Total dataset size:", len(df))

# =========================
# 3. Map Ratings → Labels
# =========================
def map_sentiment(r):
    if r >= 3.5:
        return 2  # positive
    elif r >= 2.5:
        return 1  # neutral
    else:
        return 0  # negative

df["label"] = df["star_rating"].apply(map_sentiment)

# =========================
# 4. Year Buckets (for later)
# =========================
def year_bucket(y):
    if y < 1990:
        return "Pre-1990"
    elif y < 2010:
        return "1990-2009"
    else:
        return "2010+"

df["year_group"] = df["year"].apply(year_bucket)

# =========================
# 5. Train/Test Split
# =========================
train_df, test_df = train_test_split(
    df[["movie_title", "review_text", "label", "source", "year_group"]],
    test_size=0.2,
    stratify=df["label"],
    random_state=42
)

# =========================
# 6. BASELINE MODEL
# =========================
print("\n--- Baseline Model ---")

baseline_model = pipeline("sentiment-analysis")

def convert_label(output):
    if output["label"] == "POSITIVE":
        return 2
    else:
        return 0

baseline_preds = baseline_model(list(test_df["review_text"]))
baseline_preds = [convert_label(p) for p in baseline_preds]

test_df = test_df.reset_index(drop=True)
test_df["baseline_pred"] = baseline_preds

print("\nBaseline Accuracy:",
      accuracy_score(test_df["label"], baseline_preds))

print("\nBaseline Report:")
print(classification_report(test_df["label"], baseline_preds))

# =========================
# Baseline by Source
# =========================
print("\n--- Baseline Accuracy by Source ---")
for group in test_df["source"].unique():
    subset = test_df[test_df["source"] == group]
    acc = accuracy_score(subset["label"], subset["baseline_pred"])
    print(f"{group}: {acc:.3f}")

# =========================
# 6B. IMDB BASELINE MODEL
# =========================
print("\n--- IMDB Baseline Model ---")

imdb_model = pipeline(
    "sentiment-analysis",
    model="textattack/bert-base-uncased-imdb"
)

imdb_preds = imdb_model(list(test_df["review_text"]))

def convert_label_imdb(output):
    if output["label"] == "LABEL_1":
        return 2
    else:
        return 0  # still binary

imdb_preds = [convert_label_imdb(p) for p in imdb_preds]

test_df["imdb_pred"] = imdb_preds

# Overall accuracy
print("\nIMDB Baseline Accuracy:",
      accuracy_score(test_df["label"], imdb_preds))

print("\nIMDB Classification Report:")
print(classification_report(test_df["label"], imdb_preds))

# =========================
# IMDB Accuracy by Source
# =========================
print("\n--- IMDB Accuracy by Source ---")

for group in test_df["source"].unique():
    subset = test_df[test_df["source"] == group]
    acc = accuracy_score(subset["label"], subset["imdb_pred"])
    print(f"{group}: {acc:.3f}")

# =========================
# 7. HuggingFace Dataset
# =========================
train_dataset = Dataset.from_pandas(train_df[["review_text", "label"]])
test_dataset = Dataset.from_pandas(test_df[["review_text", "label"]])

# =========================
# 8. Tokenization
# =========================
model_name = "distilbert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(model_name)

def tokenize(batch):
    return tokenizer(batch["review_text"], truncation=True, padding=True)

train_dataset = train_dataset.map(tokenize, batched=True)
test_dataset = test_dataset.map(tokenize, batched=True)

train_dataset = train_dataset.remove_columns(["review_text"])
test_dataset = test_dataset.remove_columns(["review_text"])

train_dataset.set_format("torch")
test_dataset.set_format("torch")

# =========================
# 9. Model
# =========================
model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    num_labels=3
)

# =========================
# 10. Training Setup
# =========================
training_args = TrainingArguments(
    output_dir="./results",
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    eval_strategy="epoch",
    save_strategy="no",
    logging_dir="./logs"
)

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=1)
    return {"accuracy": accuracy_score(labels, preds)}

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    compute_metrics=compute_metrics
)

# =========================
# 11. Train
# =========================
print("\n--- Training ---")
trainer.train()

# =========================
# 12. Evaluate
# =========================
print("\n--- Finetuned Model ---")

predictions = trainer.predict(test_dataset)
preds = np.argmax(predictions.predictions, axis=1)

test_df["finetuned_pred"] = preds

print("\nFinetuned Accuracy:",
      accuracy_score(test_df["label"], preds))

print("\nFinetuned Report:")
print(classification_report(test_df["label"], preds))

# =========================
# Finetuned by Source
# =========================
print("\n--- Finetuned Accuracy by Source ---")
for group in test_df["source"].unique():
    subset = test_df[test_df["source"] == group]
    acc = accuracy_score(subset["label"], subset["finetuned_pred"])
    print(f"{group}: {acc:.3f}")

# =========================
# 13. Confusion Matrix Plot
# =========================
def plot_confusion_matrix(y_true, y_pred, title):
    cm = confusion_matrix(y_true, y_pred)

    plt.figure()
    plt.imshow(cm)
    plt.title(title)
    plt.colorbar()

    labels = ["Neg", "Neu", "Pos"]
    ticks = np.arange(len(labels))

    plt.xticks(ticks, labels)
    plt.yticks(ticks, labels)

    for i in range(cm.shape[0]):
        for j in range(cm.shape[1]):
            plt.text(j, i, cm[i, j],
                     ha="center", va="center")

    plt.xlabel("Predicted")
    plt.ylabel("True")
    plt.tight_layout()
    plt.show()

plot_confusion_matrix(
    test_df["label"],
    test_df["finetuned_pred"],
    "Finetuned Confusion Matrix"
)

# =========================
# 14. Error Analysis
# =========================
print("\n--- Sample Sibling Errors ---")

for i in range(len(test_df)):
    if (test_df.loc[i, "source"] == "sibling" and
        test_df.loc[i, "label"] != test_df.loc[i, "finetuned_pred"]):

        print("\n---")
        print("Movie:", test_df.loc[i, "movie_title"])
        print("Review:", test_df.loc[i, "review_text"])
        print("True:", test_df.loc[i, "label"])
        print("Pred:", test_df.loc[i, "finetuned_pred"])

# =========================
# 15. Year-Based Analysis
# =========================
print("\n--- Review Distribution by Year Group ---")

group_counts = df.groupby(["year_group", "source"]).size().unstack(fill_value=0)
print(group_counts)

print("\n--- Proportion by Year Group ---")

group_props = group_counts.div(group_counts.sum(axis=1), axis=0)
print(group_props)

group_props.plot(kind="bar")

plt.title("Review Style Distribution by Movie Year")
plt.xlabel("Year Group")
plt.ylabel("Proportion")
plt.xticks(rotation=0)
plt.legend(title="Source")

plt.tight_layout()
plt.show()

# =========================
# 16. Accuracy by Year Group
# =========================
print("\n--- Accuracy by Year Group (Finetuned) ---")

for group in test_df["year_group"].unique():
    subset = test_df[test_df["year_group"] == group]
    acc = accuracy_score(subset["label"], subset["finetuned_pred"])
    print(f"{group}: {acc:.3f}")

# =========================
# 17. Model Comparison Summary
# =========================
print("\n=== MODEL COMPARISON ===")

models = ["baseline_pred", "imdb_pred", "finetuned_pred"]

for model_name in models:
    print(f"\n--- {model_name} ---")

    overall = accuracy_score(test_df["label"], test_df[model_name])
    print(f"Overall Accuracy: {overall:.3f}")

    for group in test_df["source"].unique():
        subset = test_df[test_df["source"] == group]
        acc = accuracy_score(subset["label"], subset[model_name])
        print(f"{group}: {acc:.3f}")